channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package.
  # Installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.10.4

  - pip=22.0.4
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==13.3.1 # https://rpaframework.org/releasenotes.html